In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.decomposition import PCA

df = pd.read_csv("../data/comprovantes_pix_10000_anomalias.csv", sep=";")

In [2]:
df.head(5)

,EndToEndId,DataHora,Valor,Moeda,Pagador_Nome,Pagador_CPF_CNPJ,Pagador_Banco,Recebedor_Nome,Recebedor_CPF_CNPJ,Recebedor_Banco,ChavePix_Utilizada,TipoChave,Descricao,Status,Anomalia
0,f094cb2c-2a73-463c-b60e-0c57262051e4,2025-06-26 21:07:56,4658.86,BRL,Nathan Cardoso,13.253.967/0001-95,BTG Pactual,Ana Beatriz Ramos,901.361.580-95,Nubank,+559694830-9884,Telefone,Pagamento referente ao serviço 927,Concluída,0
1,f0409769-741f-49bd-811a-3842cc8f54db,2025-06-23 17:47:56,3184.72,BRL,Benjamin Barros,781.515.544-64,Banco do Brasil,Carlos Eduardo Nunes,288.758.607-72,Itaú Unibanco,+552298530-1917,Telefone,Pagamento referente ao serviço 950,Pendente,0
2,c1d22287-d343-4c91-b03d-dbe9a69695b3,2025-06-27 15:58:56,1054.48,BRL,Lorena Cunha,444.922.709-96,Banco Inter,Lívia Silveira,530.827.935-48,Bradesco,c4f4c3c6-4d78-4946-b33e-4a1135711a8a,Chave Aleatória,Pagamento referente ao serviço 173,Pendente,0
3,254423a9-50b7-41b1-a099-e8cf6232bab4,2025-07-15 13:59:56,3564.76,BRL,Sra. Luana Pinto,468.153.904-62,Banco Safra,Helena Pires,827.707.674-51,Caixa Econômica Federal,user421@email.com,E-mail,Pagamento referente ao serviço 560,Estornada,0
4,f1c5e3e7-bc62-4f18-91e3-c8f92aebdd59,2025-06-23 06:19:56,15.16,BRL,João Miguel da Cunha,83.407.726/0001-68,Santander Brasil,Dr. Luiz Felipe Dias,65.245.322/0001-12,C6 Bank,user97@email.com,E-mail,Pagamento referente ao serviço 140,Pendente,0

In [12]:
contagens = df["Pagador_CPF_CNPJ"].value_counts()
cpfs_repetidos = contagens[contagens > 1]
print(cpfs_repetidos)

Pagador_CPF_CNPJ
000.000.000-00    17
Name: count, dtype: int64

In [14]:
df[df["Pagador_CPF_CNPJ"] == '000.000.000-00'].head()

,EndToEndId,DataHora,Valor,Moeda,Pagador_Nome,Pagador_CPF_CNPJ,Pagador_Banco,Recebedor_Nome,Recebedor_CPF_CNPJ,Recebedor_Banco,ChavePix_Utilizada,TipoChave,Descricao,Status,Anomalia
1472,72d81e3d-ffed-4b5e-a8e1-30c5f8cfcb9a,2025-08-11 00:56:56,3356.49,BRL,Yuri Aragão,000.000.000-00,C6 Bank,Vinicius Correia,84.984.180/0001-13,Nubank,+559594778-7196,Telefone,Pagamento referente ao serviço 21,Estornada,1
1922,a89137c8-b18e-44f5-ac30-e078c5099cb0,2025-07-30 23:17:56,3413.02,BRL,Dr. Cauê Alves,000.000.000-00,BTG Pactual,Sra. Ana da Rocha,85.327.682/0001-10,Banco Original,user479@email.com,E-mail,Pagamento referente ao serviço 55,Estornada,1
1934,2d2e394a-a521-4f27-8df4-71a33741b806,2025-08-05 07:15:56,560.37,BRL,Isis da Costa,000.000.000-00,Santander Brasil,Luiz Gustavo Jesus,54.517.456/0001-75,Banco do Brasil,9876e8d3-e3b4-4825-ab96-82964b75c0dd,Chave Aleatória,Pagamento referente ao serviço 585,Estornada,1
3270,ac85f498-ec0c-469c-8f6a-3967b1473805,2025-07-12 07:02:56,4364.75,BRL,Dr. João Vitor Aragão,000.000.000-00,Banco Original,Kevin Porto,945.830.159-93,Banco Safra,37.788.979/0001-37,CNPJ,Pagamento referente ao serviço 370,Pendente,1
3369,a093c807-4f78-4e55-94c7-0c16478a88d2,2025-08-04 17:05:56,3880.57,BRL,Ana Farias,000.000.000-00,Banco Inter,Emanuelly Nunes,82.128.390/0001-52,BTG Pactual,47.107.312/0001-33,CNPJ,Pagamento referente ao serviço 134,Concluída,1

In [11]:
contagens = df["Recebedor_CPF_CNPJ"].value_counts()
cpfs_repetidos = contagens[contagens > 1]
print(cpfs_repetidos)

Series([], Name: count, dtype: int64)

In [16]:
contagens = df["ChavePix_Utilizada"].value_counts()
chaves_repetidas = contagens[contagens > 1]
print(chaves_repetidas)

ChavePix_Utilizada
user439@email.com    8
user773@email.com    8
user941@email.com    7
user238@email.com    7
user421@email.com    7
                    ..
user929@email.com    2
user77@email.com     2
user522@email.com    2
user540@email.com    2
user542@email.com    2
Name: count, Length: 578, dtype: int64

In [19]:
len(chaves_repetidas)

578

In [20]:
df[df["ChavePix_Utilizada"] == 'user439@email.com'].head()

,EndToEndId,DataHora,Valor,Moeda,Pagador_Nome,Pagador_CPF_CNPJ,Pagador_Banco,Recebedor_Nome,Recebedor_CPF_CNPJ,Recebedor_Banco,ChavePix_Utilizada,TipoChave,Descricao,Status,Anomalia
581,bdd2683b-56c7-46f3-931a-3df41b12f90d,2025-07-31 02:24:56,2134.56,BRL,Heloísa Sales,858.769.872-17,Banco do Brasil,Júlia Araújo,53.360.920/0001-30,Banco do Brasil,user439@email.com,E-mail,Pagamento referente ao serviço 270,Concluída,0
3056,2feab330-3db7-41b8-93e3-da6bc4c2d019,2025-06-26 10:26:56,4816.32,BRL,Danilo Araújo,539.696.707-42,Banco Original,Gustavo Melo,23.158.781/0001-25,Banco Safra,user439@email.com,E-mail,Pagamento referente ao serviço 836,Estornada,0
3514,223cd7e5-03fa-43b6-99eb-b4f7c6c22d7f,2025-08-03 10:41:56,1012.81,BRL,Cecília da Mata,967.245.552-41,Bradesco,Luiz Gustavo Porto,64.631.359/0001-94,Santander Brasil,user439@email.com,E-mail,Pagamento referente ao serviço 760,Pendente,0
5341,9e7354bc-1bef-46f3-b082-cc01245372a0,2025-06-28 16:05:56,1714.66,BRL,Letícia Costa,69.284.533/0001-28,Banco Safra,Sarah da Rocha,385.383.966-59,Banco Safra,user439@email.com,E-mail,Pagamento referente ao serviço 427,Estornada,0
5530,9bc75c09-78e6-4c83-b9e5-f41b4d593ab4,2025-07-30 12:57:56,1394.23,BRL,Lorenzo Gomes,26.833.501/0001-76,Nubank,Emanuelly Mendes,30.596.621/0001-71,Banco Original,user439@email.com,E-mail,Pagamento referente ao serviço 703,Concluída,0

In [4]:
df.sort_values("Pagador_CPF_CNPJ").head(10)

,EndToEndId,DataHora,Valor,Moeda,Pagador_Nome,Pagador_CPF_CNPJ,Pagador_Banco,Recebedor_Nome,Recebedor_CPF_CNPJ,Recebedor_Banco,ChavePix_Utilizada,TipoChave,Descricao,Status,Anomalia
1922,a89137c8-b18e-44f5-ac30-e078c5099cb0,2025-07-30 23:17:56,3413.02,BRL,Dr. Cauê Alves,000.000.000-00,BTG Pactual,Sra. Ana da Rocha,85.327.682/0001-10,Banco Original,user479@email.com,E-mail,Pagamento referente ao serviço 55,Estornada,1
1472,72d81e3d-ffed-4b5e-a8e1-30c5f8cfcb9a,2025-08-11 00:56:56,3356.49,BRL,Yuri Aragão,000.000.000-00,C6 Bank,Vinicius Correia,84.984.180/0001-13,Nubank,+559594778-7196,Telefone,Pagamento referente ao serviço 21,Estornada,1
3891,46b018ef-33cf-4ab8-8405-66f8d726202f,2025-08-07 09:27:56,497.22,BRL,Alexia Santos,000.000.000-00,C6 Bank,Sra. Camila Moura,32.265.945/0001-45,Santander Brasil,87.160.988/0001-63,CNPJ,Pagamento referente ao serviço 376,Concluída,1
4963,fc7f3bdd-8190-4c62-a121-ac8f017856f8,2025-06-23 20:15:56,2504.33,BRL,Dr. Marcos Vinicius Pires,000.000.000-00,BTG Pactual,Kaique Sales,184.472.395-63,Banco Original,user22@email.com,E-mail,Pagamento referente ao serviço 936,Pendente,1
6951,00f89b45-c665-43d7-8504-53434582451a,2025-08-15 00:36:57,4266.53,BRL,Enrico Rodrigues,000.000.000-00,Nubank,Stephany Gonçalves,115.873.930-82,Banco Safra,user940@email.com,E-mail,Pagamento referente ao serviço 211,Estornada,1
6006,7137f614-f0b5-4823-ad00-7b44f3817e4c,2025-08-14 13:36:56,1082.81,BRL,Luiz Otávio da Conceição,000.000.000-00,Nubank,Juliana Nogueira,54.404.630/0001-58,C6 Bank,11.613.433/0001-56,CNPJ,Pagamento referente ao serviço 985,Pendente,1
9080,5df6d713-6f3c-4857-9a67-2d7fed50a925,2025-08-05 16:13:57,4128.97,BRL,Stella Souza,000.000.000-00,C6 Bank,Sr. Carlos Eduardo Carvalho,317.827.741-43,Banco Original,36.312.939/0001-81,CNPJ,Pagamento referente ao serviço 429,Estornada,1
6845,378e98da-2f0e-42f1-a1b3-8d7b2a06591c,2025-07-30 13:43:57,752.63,BRL,Mariana Rocha,000.000.000-00,Banco Safra,Pedro Miguel Porto,68.963.237/0001-85,Bradesco,55.350.561/0001-90,CNPJ,Pagamento referente ao serviço 864,Concluída,1
4902,55f26e73-9384-40a4-a672-ce17eca3e86b,2025-08-06 23:12:56,587.92,BRL,Daniel da Costa,000.000.000-00,C6 Bank,Nicole Costela,79.822.923/0001-75,Banco Pan,727f86a9-3664-49f3-b2c6-b92564f4d517,Chave Aleatória,Pagamento referente ao serviço 9,Pendente,1
7152,b980f8a7-1fa7-4d2c-bee9-fba5e87f354e,2025-07-29 18:01:57,4067.99,BRL,Julia Fernandes,000.000.000-00,Bradesco,André da Conceição,917.884.574-56,Itaú Unibanco,+555892961-6829,Telefone,Pagamento referente ao serviço 691,Estornada,1